/* Dữ liệu từ vựng + mẫu câu — Tiếng Anh 3, Global Success (NXB Giáo Dục VN + Macmillan)
   Đã đối chiếu nhiều vòng: giáo án 1 cột, mindmap tổng hợp, đề cương, đề thi thật
   gắn nhãn Global Success, và slide bài giảng theo đúng chương trình. */

const DATA = [
 {u:1, t:"Hello", w:[
   {en:"hello",    ipa:"/həˈləʊ/",        vi:"Xin chào",     ex:"Hello! I'm Nam."},
   {en:"hi",       ipa:"/haɪ/",            vi:"Xin chào",     ex:"Hi, Mai!"},
   {en:"goodbye",  ipa:"/ˌɡʊdˈbaɪ/",       vi:"Tạm biệt",     ex:"Goodbye! See you tomorrow."},
   {en:"how",      ipa:"/haʊ/",            vi:"Như thế nào",  ex:"How are you?"},
   {en:"fine",     ipa:"/faɪn/",           vi:"Ổn, khoẻ",     ex:"I'm fine, thank you."},
   {en:"thank you",ipa:"/ˈθæŋk juː/",      vi:"Cảm ơn",       ex:"Thank you very much."},
   {en:"thanks",   ipa:"/θæŋks/",          vi:"Cảm ơn (thân mật)", ex:"Thanks a lot!"},
   {en:"I",        ipa:"/aɪ/",             vi:"Tôi",          ex:"I am Nam."},
   {en:"you",      ipa:"/juː/",            vi:"Bạn",          ex:"You are my friend."},
   {en:"nice to meet you", ipa:"/naɪs tə miːt juː/", vi:"Rất vui được gặp bạn", ex:"Nice to meet you, Mai."},
   {en:"bye",      ipa:"/baɪ/",            vi:"Tạm biệt (thân mật)", ex:"Bye! See you later."}
 ]},
 {u:2, t:"Our names", w:[
   {en:"my",   ipa:"/maɪ/",  vi:"Của tôi", ex:"My name's Linh."},
   {en:"name", ipa:"/neɪm/", vi:"Tên",     ex:"What's your name?"},
   {en:"your", ipa:"/jɔː(r)/", vi:"Của bạn", ex:"What's your name?"},
   {en:"old",  ipa:"/əʊld/", vi:"Tuổi",    ex:"How old are you?"},
   {en:"how old", ipa:"/haʊ əʊld/", vi:"Bao nhiêu tuổi", ex:"How old are you?"},
   {en:"years old", ipa:"/jɪəz əʊld/", vi:"...tuổi", ex:"I'm eight years old."},
   {en:"what", ipa:"/wɒt/",  vi:"Cái gì",  ex:"What's this?"},
   {en:"one",   ipa:"/wʌn/",   vi:"Một",  ex:"I have one book.",  cat:"number"},
   {en:"two",   ipa:"/tuː/",   vi:"Hai",  ex:"I have two pens.",  cat:"number"},
   {en:"three", ipa:"/θriː/",  vi:"Ba",   ex:"I have three cats.", cat:"number"},
   {en:"four",  ipa:"/fɔː(r)/", vi:"Bốn", ex:"I have four rulers.", cat:"number"},
   {en:"five",  ipa:"/faɪv/",  vi:"Năm",  ex:"I have five fish.",  cat:"number"},
   {en:"six",   ipa:"/sɪks/",  vi:"Sáu",  ex:"I have six toys.",   cat:"number"},
   {en:"seven", ipa:"/ˈsevn/", vi:"Bảy",  ex:"I have seven birds.", cat:"number"},
   {en:"eight", ipa:"/eɪt/",   vi:"Tám",  ex:"I'm eight years old.", cat:"number"},
   {en:"nine",  ipa:"/naɪn/",  vi:"Chín", ex:"I have nine pencils.", cat:"number"},
   {en:"ten",   ipa:"/ten/",   vi:"Mười", ex:"I have ten fingers.", cat:"number"}
 ]},
 {u:3, t:"Our friends", w:[
   {en:"friend",  ipa:"/frend/",       vi:"Bạn bè",        ex:"This is my friend.", img:"friend"},
   {en:"Mr",      ipa:"/ˈmɪstə(r)/",  vi:"Ông, thầy",     ex:"This is Mr Long.",   img:"mr"},
   {en:"Ms",      ipa:"/mɪz/",         vi:"Cô",            ex:"This is Ms Hoa.",    img:"ms"},
   {en:"teacher", ipa:"/ˈtiːtʃə(r)/",  vi:"Giáo viên",     ex:"She is my teacher.", img:"teacher"},
   {en:"it",      ipa:"/ɪt/",          vi:"Nó",            ex:"It is a cat."},
   {en:"yes",     ipa:"/jes/",         vi:"Vâng, có",      ex:"Yes, it is."},
   {en:"no",      ipa:"/nəʊ/",         vi:"Không",         ex:"No, it isn't."},
   {en:"this",    ipa:"/ðɪs/",         vi:"Cái này, đây",  ex:"This is my book."},
   {en:"that",    ipa:"/ðæt/",         vi:"Cái kia, đó",   ex:"That is your pen."}
 ]},
 {u:4, t:"Our bodies", w:[
   {en:"ear",     ipa:"/ɪə(r)/",     vi:"Tai",         ex:"This is my ear.",          img:"ear"},
   {en:"eye",     ipa:"/aɪ/",        vi:"Mắt",         ex:"Open your eyes.",          img:"eye"},
   {en:"face",    ipa:"/feɪs/",      vi:"Khuôn mặt",   ex:"Wash your face.",          img:"face"},
   {en:"hair",    ipa:"/heə(r)/",    vi:"Tóc",         ex:"My hair is black.",        img:"hair"},
   {en:"hand",    ipa:"/hænd/",      vi:"Bàn tay",     ex:"Touch your hand.",         img:"hand"},
   {en:"mouth",   ipa:"/maʊθ/",      vi:"Miệng",       ex:"Open your mouth.",         img:"mouth"},
   {en:"nose",    ipa:"/nəʊz/",      vi:"Mũi",         ex:"Touch your nose.",         img:"nose"},
   {en:"head",    ipa:"/hed/",       vi:"Đầu",         ex:"Touch your head."},
   {en:"shoulder",ipa:"/ˈʃəʊldə(r)/",vi:"Vai",         ex:"Touch your shoulder."},
   {en:"arm",     ipa:"/ɑːm/",       vi:"Cánh tay",    ex:"Touch your arm."},
   {en:"elbow",   ipa:"/ˈelbəʊ/",    vi:"Khuỷu tay",   ex:"Touch your elbow."},
   {en:"finger",  ipa:"/ˈfɪŋɡə(r)/", vi:"Ngón tay",    ex:"Touch your finger."},
   {en:"body",    ipa:"/ˈbɒdi/",     vi:"Cơ thể",      ex:"This is my body."},
   {en:"leg",     ipa:"/leɡ/",       vi:"Chân",        ex:"Touch your leg."},
   {en:"knee",    ipa:"/niː/",       vi:"Đầu gối",     ex:"Touch your knee."},
   {en:"foot",    ipa:"/fʊt/",       vi:"Bàn chân",    ex:"Touch your foot."},
   {en:"toe",     ipa:"/təʊ/",       vi:"Ngón chân",   ex:"Touch your toe."},
   {en:"touch",   ipa:"/tʌtʃ/",      vi:"Chạm",        ex:"Touch your ear."},
   {en:"open",    ipa:"/ˈəʊpən/",    vi:"Mở",          ex:"Open your eyes."},
   {en:"close",   ipa:"/kləʊz/",     vi:"Đóng, nhắm",  ex:"Close your eyes."}
 ]},
 {u:5, t:"My hobbies", w:[
   {en:"hobby",    ipa:"/ˈhɒbi/",    vi:"Sở thích", ex:"What's your hobby?"},
   {en:"cooking",  ipa:"/ˈkʊkɪŋ/",   vi:"Nấu ăn",   ex:"My hobby is cooking.",  img:"cooking"},
   {en:"dancing",  ipa:"/ˈdɑːnsɪŋ/", vi:"Nhảy múa", ex:"She likes dancing.",    img:"dancing"},
   {en:"drawing",  ipa:"/ˈdrɔːɪŋ/",  vi:"Vẽ",       ex:"He likes drawing.",     img:"drawing"},
   {en:"painting", ipa:"/ˈpeɪntɪŋ/", vi:"Tô màu, sơn", ex:"I like painting.",   img:"painting"},
   {en:"running",  ipa:"/ˈrʌnɪŋ/",   vi:"Chạy",     ex:"My hobby is running.",  img:"running"},
   {en:"singing",  ipa:"/ˈsɪŋɪŋ/",   vi:"Hát",      ex:"She likes singing.",    img:"singing"},
   {en:"swimming", ipa:"/ˈswɪmɪŋ/",  vi:"Bơi",      ex:"I like swimming.",      img:"swimming"},
   {en:"walking",  ipa:"/ˈwɔːkɪŋ/",  vi:"Đi bộ",    ex:"He likes walking.",     img:"walking"}
 ]},
 {u:6, t:"Our school", w:[
   {en:"art room",        ipa:"/ɑːt ruːm/",              vi:"Phòng hội hoạ",     ex:"The art room is big.",       img:"artroom"},
   {en:"classroom",       ipa:"/ˈklɑːsruːm/",            vi:"Phòng học",         ex:"This is my classroom.",      img:"classroom"},
   {en:"computer room",   ipa:"/kəmˈpjuːtə(r) ruːm/",    vi:"Phòng máy tính",    ex:"Where's the computer room?", img:"computerroom"},
   {en:"gym",             ipa:"/dʒɪm/",                   vi:"Phòng thể chất",    ex:"We play in the gym.",        img:"gym"},
   {en:"library",         ipa:"/ˈlaɪbrəri/",              vi:"Thư viện",          ex:"I read books in the library.", img:"library"},
   {en:"music room",      ipa:"/ˈmjuːzɪk ruːm/",          vi:"Phòng nhạc",        ex:"We sing in the music room.", img:"musicroom"},
   {en:"playground",      ipa:"/ˈpleɪɡraʊnd/",            vi:"Sân chơi",          ex:"We play in the playground.", img:"playground"},
   {en:"school",          ipa:"/skuːl/",                   vi:"Trường học",        ex:"I go to school.",            img:"school"}
 ]},
 {u:7, t:"Classroom instructions", w:[
   {en:"please",         ipa:"/pliːz/",              vi:"Làm ơn",         ex:"Sit down, please."},
   {en:"open your book",  ipa:"/ˈəʊpən jɔː(r) bʊk/", vi:"Mở sách của bạn ra", ex:"Open your book, please."},
   {en:"close your book", ipa:"/kləʊz jɔː(r) bʊk/",  vi:"Đóng sách của bạn lại", ex:"Close your book, please."},
   {en:"come in",   ipa:"/kʌm ɪn/",    vi:"Vào đi",     ex:"Come in, please."},
   {en:"go out",    ipa:"/ɡəʊ aʊt/",   vi:"Ra ngoài",   ex:"Go out and play."},
   {en:"sit down",  ipa:"/sɪt daʊn/",  vi:"Ngồi xuống", ex:"Sit down, please."},
   {en:"speak Vietnamese", ipa:"/spiːk ˌvjetnəˈmiːz/", vi:"Nói tiếng Việt", ex:"May I speak Vietnamese?"},
   {en:"stand up",  ipa:"/stænd ʌp/",  vi:"Đứng lên",   ex:"Stand up, please."},
   {en:"hands up",  ipa:"/hændz ʌp/", vi:"Giơ tay lên", ex:"Hands up, please."},
   {en:"hands down",ipa:"/hændz daʊn/", vi:"Bỏ tay xuống", ex:"Hands down, please."}
 ]},
 {u:8, t:"My school things", w:[
   {en:"book",         ipa:"/bʊk/",             vi:"Quyển sách", ex:"This is my book.",         img:"book"},
   {en:"eraser",       ipa:"/ɪˈreɪzə(r)/",      vi:"Cục tẩy",    ex:"I have an eraser.",         img:"eraser"},
   {en:"notebook",     ipa:"/ˈnəʊtbʊk/",        vi:"Vở ghi",     ex:"Open your notebook.",       img:"notebook"},
   {en:"pen",          ipa:"/pen/",              vi:"Bút mực",    ex:"This is my pen.",           img:"pen"},
   {en:"pencil",       ipa:"/ˈpensl/",          vi:"Bút chì",    ex:"I write with a pencil.",    img:"pencil"},
   {en:"pencil case",  ipa:"/ˈpensl keɪs/",     vi:"Hộp bút",    ex:"My pencil case is blue.",   img:"pencilcase"},
   {en:"pencil sharpener", ipa:"/ˈpensl ʃɑːpənə(r)/", vi:"Gọt bút chì", ex:"I have a pencil sharpener."},
   {en:"ruler",        ipa:"/ˈruːlə(r)/",       vi:"Thước kẻ",   ex:"Give me the ruler.",        img:"ruler"},
   {en:"school bag",   ipa:"/skuːl bæɡ/",        vi:"Cặp sách",   ex:"This is my school bag.",    img:"schoolbag"}
 ]},
 {u:9, t:"Colours", w:[
   {en:"colour",  ipa:"/ˈkʌlə(r)/",    vi:"Màu sắc",       ex:"What colour is it?"},
   {en:"they",    ipa:"/ðeɪ/",          vi:"Họ, chúng",     ex:"They are red."},
   {en:"black",   ipa:"/blæk/",         vi:"Màu đen",       ex:"My hair is black.",   img:"swatch", swatch:"#1c1c1c"},
   {en:"blue",    ipa:"/bluː/",         vi:"Màu xanh dương", ex:"The sky is blue.",   img:"swatch", swatch:"#2f6fed"},
   {en:"brown",   ipa:"/braʊn/",        vi:"Màu nâu",       ex:"The table is brown.", img:"swatch", swatch:"#8a5a34"},
   {en:"green",   ipa:"/ɡriːn/",        vi:"Màu xanh lá",   ex:"The tree is green.",  img:"swatch", swatch:"#3ecf8e"},
   {en:"orange",  ipa:"/ˈɒrɪndʒ/",      vi:"Màu cam",       ex:"I like orange.",      img:"swatch", swatch:"#ff8a3c"},
   {en:"red",     ipa:"/red/",          vi:"Màu đỏ",        ex:"The apple is red.",   img:"swatch", swatch:"#ff4d4d"},
   {en:"white",   ipa:"/waɪt/",         vi:"Màu trắng",     ex:"My shirt is white.",  img:"swatch", swatch:"#f4f6fb"},
   {en:"yellow",  ipa:"/ˈjeləʊ/",       vi:"Màu vàng",      ex:"The sun is yellow.",  img:"swatch", swatch:"#ffd23c"},
   {en:"pink",    ipa:"/pɪŋk/",         vi:"Màu hồng",      ex:"My pencil case is pink.", img:"swatch", swatch:"#ff8ac6"},
   {en:"purple",  ipa:"/ˈpɜːpl/",       vi:"Màu tím",       ex:"I like purple.",      img:"swatch", swatch:"#9b5de5"},
   {en:"grey",    ipa:"/ɡreɪ/",         vi:"Màu xám",       ex:"The elephant is grey.", img:"swatch", swatch:"#9aa1ad"}
 ]},
 {u:10, t:"Break time activities", w:[
   {en:"break time",    ipa:"/breɪk taɪm/",       vi:"Giờ ra chơi", ex:"It's break time!"},
   {en:"chat",          ipa:"/tʃæt/",              vi:"Trò chuyện",  ex:"We chat at break time."},
   {en:"badminton",     ipa:"/ˈbædmɪntən/",       vi:"Cầu lông",    ex:"I play badminton.",     img:"badminton"},
   {en:"basketball",    ipa:"/ˈbɑːskɪtbɔːl/",     vi:"Bóng rổ",     ex:"He plays basketball.",  img:"basketball"},
   {en:"chess",         ipa:"/tʃes/",              vi:"Cờ vua",      ex:"They play chess.",      img:"chess"},
   {en:"football",      ipa:"/ˈfʊtbɔːl/",         vi:"Bóng đá",     ex:"We play football.",     img:"football"},
   {en:"table tennis",  ipa:"/ˈteɪbl ˈtenɪs/",    vi:"Bóng bàn",    ex:"I play table tennis.",  img:"tabletennis"},
   {en:"volleyball",    ipa:"/ˈvɒlibɔːl/",         vi:"Bóng chuyền", ex:"They play volleyball.", img:"volleyball"},
   {en:"word puzzle",   ipa:"/wɜːd ˈpʌzl/",        vi:"Trò chơi ô chữ", ex:"I do a word puzzle at break time."}
 ]},
 {u:11, t:"My family", w:[
   {en:"family",     ipa:"/ˈfæməli/",       vi:"Gia đình",  ex:"This is my family.", cat:"family"},
   {en:"parents",    ipa:"/ˈpeərənts/",     vi:"Bố mẹ",           ex:"These are my parents.", cat:"family"},
   {en:"grandparents",ipa:"/ˈɡrænpeərənts/",vi:"Ông bà",          ex:"These are my grandparents.", cat:"family"},
   {en:"father",     ipa:"/ˈfɑːðə(r)/",     vi:"Bố",              ex:"This is my father.",  img:"father", cat:"family"},
   {en:"mother",     ipa:"/ˈmʌðə(r)/",      vi:"Mẹ",              ex:"This is my mother.",  img:"mother", cat:"family"},
   {en:"brother",    ipa:"/ˈbrʌðə(r)/",     vi:"Anh trai, em trai", ex:"He is my brother.", img:"brother", cat:"family"},
   {en:"older brother", ipa:"/ˈəʊldə(r) ˈbrʌðə(r)/", vi:"Anh trai", ex:"He is my older brother.", cat:"family"},
   {en:"younger brother", ipa:"/ˈjʌŋɡə(r) ˈbrʌðə(r)/", vi:"Em trai", ex:"He is my younger brother.", cat:"family"},
   {en:"sister",     ipa:"/ˈsɪstə(r)/",     vi:"Chị gái, em gái", ex:"She is my sister.",   img:"sister", cat:"family"},
   {en:"older sister", ipa:"/ˈəʊldə(r) ˈsɪstə(r)/", vi:"Chị gái", ex:"She is my older sister.", cat:"family"},
   {en:"younger sister", ipa:"/ˈjʌŋɡə(r) ˈsɪstə(r)/", vi:"Em gái", ex:"She is my younger sister.", cat:"family"},
   {en:"grandfather",ipa:"/ˈɡrænfɑːðə(r)/", vi:"Ông",             ex:"He is my grandfather.", cat:"family"},
   {en:"grandmother",ipa:"/ˈɡrænmʌðə(r)/",  vi:"Bà",              ex:"She is my grandmother.", cat:"family"},
   {en:"aunt",       ipa:"/ɑːnt/",          vi:"Cô, dì",          ex:"She is my aunt.", cat:"family"},
   {en:"uncle",      ipa:"/ˈʌŋkl/",         vi:"Chú, cậu, bác",   ex:"He is my uncle.", cat:"family"},
   {en:"nephew",     ipa:"/ˈnefjuː/",       vi:"Cháu trai",       ex:"He is my nephew.", cat:"family"},
   {en:"eleven",     ipa:"/ɪˈlevn/",        vi:"Mười một",  ex:"I have eleven pens.",  cat:"number"},
   {en:"twelve",     ipa:"/twelv/",         vi:"Mười hai",  ex:"I have twelve books.", cat:"number"},
   {en:"thirteen",   ipa:"/ˌθɜːˈtiːn/",     vi:"Mười ba",   ex:"She is thirteen years old.", cat:"number"},
   {en:"fourteen",   ipa:"/ˌfɔːˈtiːn/",     vi:"Mười bốn",  ex:"He is fourteen years old.", cat:"number"},
   {en:"fifteen",    ipa:"/ˌfɪfˈtiːn/",     vi:"Mười lăm",  ex:"I have fifteen toys.", cat:"number"},
   {en:"sixteen",    ipa:"/ˌsɪksˈtiːn/",    vi:"Mười sáu",  ex:"My sister is sixteen.", cat:"number"},
   {en:"seventeen",  ipa:"/ˌsevnˈtiːn/",    vi:"Mười bảy",  ex:"My brother is seventeen.", cat:"number"},
   {en:"eighteen",   ipa:"/ˌeɪˈtiːn/",      vi:"Mười tám",  ex:"He is eighteen years old.", cat:"number"},
   {en:"nineteen",   ipa:"/ˌnaɪnˈtiːn/",    vi:"Mười chín", ex:"I have nineteen books.", cat:"number"},
   {en:"twenty",     ipa:"/ˈtwenti/",       vi:"Hai mươi",  ex:"I have twenty pens.", cat:"number"}
 ]},
 {u:12, t:"Jobs", w:[
   {en:"job",     ipa:"/dʒɒb/",         vi:"Nghề nghiệp", ex:"What's his job?"},
   {en:"cook",    ipa:"/kʊk/",          vi:"Đầu bếp",     ex:"My father is a cook.",   img:"cook"},
   {en:"dancer",  ipa:"/ˈdɑːnsə(r)/",  vi:"Vũ công",     ex:"She is a dancer."},
   {en:"doctor",  ipa:"/ˈdɒktə(r)/",   vi:"Bác sĩ",      ex:"She is a doctor.",       img:"doctor"},
   {en:"driver",  ipa:"/ˈdraɪvə(r)/",  vi:"Tài xế",      ex:"He is a driver.",        img:"driver"},
   {en:"farmer",  ipa:"/ˈfɑːmə(r)/",   vi:"Nông dân",    ex:"My uncle is a farmer.",  img:"farmer"},
   {en:"nurse",   ipa:"/nɜːs/",         vi:"Y tá",        ex:"She is a nurse.",        img:"nurse"},
   {en:"pupil",   ipa:"/ˈpjuːpl/",     vi:"Học sinh",    ex:"He is a pupil."},
   {en:"singer",  ipa:"/ˈsɪŋə(r)/",    vi:"Ca sĩ",       ex:"He is a singer.",        img:"singer"},
   {en:"teacher", ipa:"/ˈtiːtʃə(r)/",  vi:"Giáo viên",   ex:"My mother is a teacher.", img:"teacher"},
   {en:"worker",  ipa:"/ˈwɜːkə(r)/",   vi:"Công nhân",   ex:"He is a worker.",        img:"worker"}
 ]},
 {u:13, t:"My house", w:[
   {en:"house",       ipa:"/haʊs/",             vi:"Nhà",         ex:"This is my house.",         img:"house"},
   {en:"bathroom",    ipa:"/ˈbɑːθruːm/",       vi:"Phòng tắm",   ex:"Where's the bathroom?",     img:"bathroom"},
   {en:"bedroom",     ipa:"/ˈbedruːm/",        vi:"Phòng ngủ",   ex:"This is my bedroom.",       img:"bedroom"},
   {en:"kitchen",     ipa:"/ˈkɪtʃɪn/",         vi:"Phòng bếp",   ex:"My mother is in the kitchen.", img:"kitchen"},
   {en:"living room", ipa:"/ˈlɪvɪŋ ruːm/",     vi:"Phòng khách", ex:"We watch TV in the living room.", img:"livingroom"},
   {en:"chair",       ipa:"/tʃeə(r)/",          vi:"Ghế",         ex:"Sit on the chair.",         img:"chair"},
   {en:"lamp",        ipa:"/læmp/",             vi:"Đèn",         ex:"The lamp is on the table.", img:"lamp"},
   {en:"table",       ipa:"/ˈteɪbl/",           vi:"Bàn",         ex:"The book is on the table.", img:"table"},
   {en:"here",        ipa:"/hɪə(r)/",           vi:"Đây",         ex:"Come here, please."},
   {en:"there",       ipa:"/ðeə(r)/",           vi:"Kia",         ex:"The lamp is there."},
   {en:"in",          ipa:"/ɪn/",               vi:"Trong",       ex:"The cat is in the box."},
   {en:"on",          ipa:"/ɒn/",               vi:"Trên",        ex:"The book is on the chair."}
 ]},
 {u:14, t:"My bedroom", w:[
   {en:"bed",     ipa:"/bed/",       vi:"Giường", ex:"I sleep on my bed.",  img:"bed"},
   {en:"big",     ipa:"/bɪɡ/",       vi:"To",     ex:"My room is big."},
   {en:"desk",    ipa:"/desk/",      vi:"Bàn học",  ex:"I study at my desk.", img:"desk"},
   {en:"door",    ipa:"/dɔː(r)/",    vi:"Cửa",    ex:"Close the door.",     img:"door"},
   {en:"new",     ipa:"/njuː/",      vi:"Mới",    ex:"This is a new lamp."},
   {en:"old",     ipa:"/əʊld/",      vi:"Cũ",     ex:"That is an old desk."},
   {en:"room",    ipa:"/ruːm/",      vi:"Phòng",  ex:"This is my room."},
   {en:"small",   ipa:"/smɔːl/",     vi:"Nhỏ",    ex:"The desk is small."},
   {en:"window",  ipa:"/ˈwɪndəʊ/",   vi:"Cửa sổ", ex:"Open the window.",   img:"window"}
 ]},
 {u:15, t:"At the dining table", w:[
   {en:"bean",    ipa:"/biːn/",         vi:"Hạt đậu",       ex:"I like beans.",       img:"bean"},
   {en:"bread",   ipa:"/bred/",         vi:"Bánh mì",       ex:"I eat bread.",        img:"bread"},
   {en:"chicken", ipa:"/ˈtʃɪkɪn/",     vi:"Thịt gà",       ex:"I like chicken.",     img:"chicken"},
   {en:"egg",     ipa:"/eɡ/",           vi:"Trứng",         ex:"I have an egg.",      img:"egg"},
   {en:"fish",    ipa:"/fɪʃ/",          vi:"Cá",            ex:"I like fish.",        img:"fish"},
   {en:"juice",   ipa:"/dʒuːs/",       vi:"Nước hoa quả",  ex:"I drink juice.",      img:"juice"},
   {en:"orange juice", ipa:"/ˈɒrɪndʒ dʒuːs/", vi:"Nước cam", ex:"I'd like some orange juice, please.", img:"juice"},
   {en:"meat",    ipa:"/miːt/",         vi:"Thịt",          ex:"I don't like meat.",  img:"meat"},
   {en:"milk",    ipa:"/mɪlk/",         vi:"Sữa",           ex:"I drink milk.",       img:"milk"},
   {en:"rice",    ipa:"/raɪs/",        vi:"Gạo, cơm",      ex:"I eat rice.",         img:"rice"},
   {en:"water",   ipa:"/ˈwɔːtə(r)/",   vi:"Nước",          ex:"I drink water.",      img:"water"}
 ]},
 {u:16, t:"My pets", w:[
   {en:"bird",     ipa:"/bɜːd/",         vi:"Chim",     ex:"I have a bird.",     img:"bird"},
   {en:"cat",      ipa:"/kæt/",          vi:"Mèo",      ex:"I have a cat.",      img:"cat"},
   {en:"dog",      ipa:"/dɒɡ/",          vi:"Chó",      ex:"I have a dog.",      img:"dog"},
   {en:"goldfish", ipa:"/ˈɡəʊldfɪʃ/",   vi:"Cá vàng",  ex:"I have two goldfish.", img:"goldfish"},
   {en:"parrot",   ipa:"/ˈpærət/",      vi:"Con vẹt",  ex:"I have a parrot.",   img:"parrot"},
   {en:"rabbit",   ipa:"/ˈræbɪt/",      vi:"Thỏ",      ex:"I have a rabbit.",   img:"rabbit"},
   {en:"many",     ipa:"/ˈmeni/",        vi:"Nhiều",    ex:"I have many pets."},
   {en:"some",     ipa:"/sʌm/",          vi:"Một vài",  ex:"I have some fish."}
 ]},
 {u:17, t:"Our toys", w:[
   {en:"bus",         ipa:"/bʌs/",             vi:"Xe buýt",   ex:"This is a bus.",        img:"bus"},
   {en:"car",         ipa:"/kɑː(r)/",          vi:"Ô tô",      ex:"This is my car.",       img:"car"},
   {en:"kite",        ipa:"/kaɪt/",             vi:"Diều",      ex:"I have a kite.",        img:"kite"},
   {en:"plane",       ipa:"/pleɪn/",            vi:"Máy bay",   ex:"This is a plane.",      img:"plane"},
   {en:"ship",        ipa:"/ʃɪp/",              vi:"Tàu thuỷ",  ex:"This is a ship.",       img:"ship"},
   {en:"teddy bear",  ipa:"/ˈtedi beə(r)/",    vi:"Gấu bông",  ex:"I love my teddy bear.", img:"teddybear"},
   {en:"toy",         ipa:"/tɔɪ/",              vi:"Đồ chơi",   ex:"This is my toy."},
   {en:"train",       ipa:"/treɪn/",            vi:"Tàu hoả",   ex:"I like the train.",     img:"train"},
   {en:"truck",       ipa:"/trʌk/",             vi:"Xe tải",    ex:"This is a truck.",      img:"truck"}
 ]},
 {u:18, t:"Playing and doing", w:[
   {en:"dancing",             ipa:"/ˈdɑːnsɪŋ/",                 vi:"Nhảy múa",   ex:"She is dancing.",         img:"dancing"},
   {en:"drawing a picture",   ipa:"/ˈdrɔːɪŋ ə ˈpɪktʃə(r)/",    vi:"Vẽ tranh",   ex:"He is drawing a picture.", img:"drawing"},
   {en:"listening to music",  ipa:"/ˈlɪsənɪŋ tə ˈmjuːzɪk/",    vi:"Nghe nhạc",  ex:"I am listening to music.", img:"listening"},
   {en:"playing basketball",  ipa:"/ˈpleɪɪŋ ˈbɑːskɪtbɔːl/",    vi:"Chơi bóng rổ", ex:"He is playing basketball.", img:"basketball"},
   {en:"reading",             ipa:"/ˈriːdɪŋ/",                  vi:"Đọc sách",   ex:"She is reading.",         img:"reading"},
   {en:"singing",             ipa:"/ˈsɪŋɪŋ/",                   vi:"Hát",        ex:"He is singing.",          img:"singing"},
   {en:"watching TV",         ipa:"/wɒtʃɪŋ ˌtiː ˈviː/",        vi:"Xem tivi",   ex:"They are watching TV.",   img:"watchingtv"},
   {en:"writing",             ipa:"/ˈraɪtɪŋ/",                  vi:"Viết",       ex:"I am writing.",           img:"writing"}
 ]},
 {u:19, t:"Outdoor activities", w:[
   {en:"cycling",       ipa:"/ˈsaɪklɪŋ/",       vi:"Đạp xe",     ex:"He is cycling.",        img:"cycling"},
   {en:"flying a kite", ipa:"/ˈflaɪɪŋ ə kaɪt/", vi:"Thả diều",   ex:"They are flying a kite.", img:"flyingkite"},
   {en:"painting",      ipa:"/ˈpeɪntɪŋ/",       vi:"Vẽ tranh",   ex:"She is painting.",       img:"painting"},
   {en:"running",       ipa:"/ˈrʌnɪŋ/",         vi:"Chạy",       ex:"He is running.",         img:"running"},
   {en:"skating",       ipa:"/ˈskeɪtɪŋ/",       vi:"Trượt patin", ex:"She is skating.",       img:"skating"},
   {en:"skipping",      ipa:"/ˈskɪpɪŋ/",        vi:"Nhảy dây",   ex:"They are skipping.",     img:"skipping"}
 ]},
 {u:20, t:"At the zoo", w:[
   {en:"elephant", ipa:"/ˈelɪfənt/",   vi:"Con voi",  ex:"Look at the elephant!", img:"elephant"},
   {en:"horse",    ipa:"/hɔːs/",        vi:"Con ngựa", ex:"Look at the horse!",   img:"horse"},
   {en:"monkey",   ipa:"/ˈmʌŋki/",     vi:"Con khỉ",  ex:"Look at the monkey!",  img:"monkey"},
   {en:"peacock",  ipa:"/ˈpiːkɒk/",    vi:"Con công", ex:"Look at the peacock!", img:"peacock"},
   {en:"tiger",    ipa:"/ˈtaɪɡə(r)/",  vi:"Con hổ",   ex:"Look at the tiger!",   img:"tiger"},
   {en:"dancing",  ipa:"/ˈdɑːnsɪŋ/",   vi:"Nhảy múa", ex:"The elephant is dancing.", img:"dancing"},
   {en:"swinging", ipa:"/ˈswɪŋɪŋ/",    vi:"Đu đưa",   ex:"The monkey is swinging.", img:"swinging"},
   {en:"climbing", ipa:"/ˈklaɪmɪŋ/",   vi:"Leo trèo", ex:"The monkey is climbing.", img:"climbing"},
   {en:"counting", ipa:"/ˈkaʊntɪŋ/",   vi:"Đếm",      ex:"We are counting the animals.", img:"counting"}
 ]}
];

/* Mẫu câu giao tiếp theo từng Unit — dùng cho chế độ "Luyện mẫu câu" */
const PATTERNS = {
  1:  [["Hello!","Hi!"],["Goodbye!","Bye!"],["How are you?","I'm fine, thank you."]],
  2:  [["What's your name?","My name's Linh."],["How old are you?","I'm eight years old."],["How do you spell your name?","L-I-N-D-A."]],
  3:  [["Is this your friend?","Yes, it is. / No, it isn't."],["Who's this?","This is my friend, Nam."],["Is that Ms Hoa?","Yes, it is. / No, it isn't."],["Is this Mr Long?","Yes, it is. / No, it isn't."]],
  4:  [["What's this?","It's my nose."],["Touch your ear.","Yes, teacher."],["What's that?","It's a mouth."]],
  5:  [["What's your hobby?","I like drawing."],["Do you like swimming?","Yes, I do. / No, I don't."],["What's your hobby?","It's swimming."]],
  6:  [["Where's the library?","It's over there."],["Is this the gym?","Yes, it is."],["Let's go to the art room.","OK. Let's go."],["Is this our classroom?","Yes, it is. / No, it isn't."],["Let's go to the library!","OK, let's go."]],
  7:  [["Stand up, please.","Yes, teacher."],["Open your book, please.","Yes, teacher."],["May I open the book?","Yes, you can. / No, you can't."],["May I go out?","Yes, you can. / No, you can't."]],
  8:  [["What's this?","It's a ruler."],["Is this your pencil case?","Yes, it is."],["Do you have a pencil?","Yes, I do. / No, I don't."]],
  9:  [["What colour is it?","It's red."],["Is your bag blue?","No, it's green."]],
  10: [["What do you play at break time?","I play football."],["Do you like chess?","Yes, I do."]],
  11: [["Who's this?","He's my brother."],["How many people are there in your family?","There are four."],["How old is your father?","He's forty years old."]],
  12: [["What's his job?","He's a doctor."],["Is she a teacher?","Yes, she is."],["What's your father's job?","He's a cook."],["Is he a doctor?","Yes, he is. / No, he isn't."]],
  13: [["Where's the living room?","It's here."],["Is the lamp on the table?","Yes, it is."],["Is there a table in the kitchen?","Yes, there is."]],
  14: [["Is your room big or small?","It's small."],["Is this a new desk?","No, it's an old desk."],["Are there two windows in your room?","Yes, there are."]],
  15: [["What would you like?","I'd like some rice, please."],["Do you like fish?","Yes, I do. / No, I don't."]],
  16: [["Have you got a pet?","Yes, I have. / No, I haven't."],["How many cats have you got?","I've got two cats."]],
  17: [["What's this?","It's a kite."],["Are these your toys?","Yes, they are."]],
  18: [["What are you doing?","I'm reading."],["What is she doing?","She's dancing."]],
  19: [["What are they doing?","They're cycling."],["Do you like flying a kite?","Yes, I do."]],
  20: [["What can you see?","I can see a tiger."],["Can you see the monkey?","Yes, I can."]]
};
